server:
  port: 8585

spring:
  application:
    name: G-Test
  cloud:
    gateway:
      mvc:
        routes:
          - id: PTest
            uri: lb://PTest
            predicates:
              - Path=/api/t/**

eureka:
  client:
    service-url:
      defaultZone: http://stest:8761/eureka/ #De här kommer behöver ändra vi docker
  instance:
    prefer-ip-address: true
