server:
  port: 8585

spring:
  application:
    name: G-Test
  cloud:
    gateway:
      mvc:
        routes:
          - id: WigellSushi
            uri: lb://WigellSushi
            predicates:
              - Path=/api/v3/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #De här kommer behöver ändra vi docker
  instance:
    prefer-ip-address: true
